In [1]:
#Import Eseential Libraries
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Import Dataset
df=pd.read_csv("wp_data.csv")
df.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [3]:
#  Dropping date column as it's of no use 
df=df.drop("date",axis=1)
df.head()

   precipitation  temp_max  temp_min  wind  weather
0            0.0      12.8       5.0   4.7  drizzle
1           10.9      10.6       2.8   4.5     rain
2            0.8      11.7       7.2   2.3     rain
3           20.3      12.2       5.6   4.7     rain
4            1.3       8.9       2.8   6.1     rain

In [4]:
df.shape

(1461, 5)

In [5]:
#Check for missing values
df.isnull().sum()

precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
dtype: int64

In [6]:
#Separate dataset into dependent and independent variables
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [7]:
#train_test_splitting
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2,random_state=0)

In [8]:
# Apply Logistic Regression Algorithm
from sklearn.linear_model import LogisticRegression
wp=LogisticRegression()
wp.fit(X_train, y_train)

LogisticRegression()

In [9]:
# Test the Model
y_pred=wp.predict(X_test)
y_pred

array(['sun', 'sun', 'rain', 'sun', 'sun', 'rain', 'rain', 'rain', 'sun',
       'rain', 'sun', 'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain',
       'rain', 'rain', 'rain', 'rain', 'rain', 'sun', 'sun', 'sun', 'sun',
       'rain', 'sun', 'sun', 'rain', 'sun', 'rain', 'rain', 'sun', 'rain',
       'sun', 'rain', 'sun', 'rain', 'sun', 'rain', 'rain', 'rain', 'sun',
       'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain',
       'rain', 'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun',
       'sun', 'sun', 'rain', 'sun', 'sun', 'sun', 'rain', 'rain', 'rain',
       'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun',
       'sun', 'rain', 'rain', 'rain', 'sun', 'sun', 'rain', 'sun', 'rain',
       'sun', 'sun', 'rain', 'sun', 'rain', 'snow', 'sun', 'sun', 'sun',
       'sun', 'rain', 'sun', 'sun', 'rain', 'rain', 'sun', 'rain', 'rain',
       'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun', 'sun',
       'sun', 'rain', 'rain', 'sun', 'rain', 'rain', 'sun', 'rain', 'sun',
       'sun', 'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'rain', 'rain',
       'rain', 'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun', 'sun',
       'sun', 'rain', 'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'sun',
       'rain', 'sun', 'rain', 'sun', 'sun', 'rain', 'sun', 'sun', 'sun',
       'rain', 'sun', 'rain', 'rain', 'sun', 'rain', 'rain', 'rain',
       'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun', 'sun', 'sun',
       'sun', 'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun',
       'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun',
       'sun', 'sun', 'sun', 'rain', 'sun', 'sun', 'sun', 'rain', 'rain',
       'rain', 'sun', 'sun', 'sun', 'snow', 'rain', 'rain', 'rain', 'sun',
       'sun', 'sun', 'rain', 'rain', 'rain', 'sun', 'sun', 'sun', 'rain',
       'sun', 'sun', 'sun', 'sun', 'rain', 'sun', 'sun', 'rain', 'rain',
       'rain', 'rain', 'sun', 'rain', 'sun', 'rain', 'rain', 'sun',
       'rain', 'sun', 'rain', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun',
       'sun', 'sun', 'rain', 'rain', 'sun', 'sun', 'sun', 'sun', 'sun',
       'sun', 'rain', 'sun', 'sun', 'sun', 'sun', 'rain', 'sun', 'rain',
       'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun', 'sun', 'sun',
       'sun', 'rain', 'sun', 'rain', 'rain', 'rain', 'sun', 'sun', 'sun',
       'rain', 'sun', 'rain', 'sun', 'sun', 'rain', 'sun'], dtype=object)

In [10]:
y_test

530     sun
657     sun
459    rain
279     sun
656     sun
       ...
440    rain
634     sun
494     sun
61     rain
517     sun
Name: weather, Length: 293, dtype: str

In [11]:
# Create confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
print(cm) #237 matched 56 mismatched total Sample = 293

[[  0   0   0   0  10]
 [  0   0   0   0  29]
 [  0   0 110   0  13]
 [  0   0   4   2   0]
 [  0   0   0   0 125]]

In [12]:
from sklearn.metrics import accuracy_score
print(f"Accuracy Score ={accuracy_score(y_pred, y_test):.2%}")

Accuracy Score =80.89%

In [13]:
import pickle
pickle.dump(wp,open("wp.pkl","wb"))
print ("Model is saved")

Model is saved